# Generated by Django 6.0.1 on 2026-04-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_sellerprofile_branch_name_sellerprofile_document_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
    ]
