# Generated by Django 6.0.1 on 2026-04-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_sellerprofile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='bank_account_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='branch_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='document_1',
            field=models.FileField(blank=True, null=True, upload_to='seller_docs/'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='document_2',
            field=models.FileField(blank=True, null=True, upload_to='seller_docs/'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='gst_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='ifsc_code',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='pan_number',
            field=models.CharField(max_length=10),
        ),
    ]
