# Generated by Django 6.0.1 on 2026-03-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_cancellable',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_returnable',
        ),
        migrations.RemoveField(
            model_name='product',
            name='return_days',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_cancellable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_returnable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='return_days',
            field=models.IntegerField(default=7),
        ),
    ]
